
add_newline = false

right_format = "$time"
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[line_break]
disabled = true

[directory]
truncate_to_repo = false

[zig]
symbol = 'âš¡ï¸ '

[python]
symbol = 'ðŸ‘¾ '
pyenv_version_name = true
